import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FBM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body
        className={inter.className}
        style={{
          display: "flex",
          overflow: "hidden",
          height: "100vh",
        }}
      >
        {children}
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
